### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by glongman** [dylanz/i18n_backend_database#1]
We are interested in using this software but we need to know what the license is. MIT? Pretty much any non GPLish would be great.

Geoff

**Comment by dylanz** [comment]
Hey Geoff.  Not a problem.
Just pushed a BSD license (specifically http://www.openbsd.org/policy.html).
So, have at it!  Thanks for the heads up... I always seem to forget about licensing ;)

**Comment by glongman** [comment]
thanks much dude.
