### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by swindsor** [dylanz/i18n_backend_database#11]
Why did you release this under such a strange license?

I'd use this, but requiring all companies to display "This product includes software developed by ELC Technologies" seems excessive.

Would you reconsider releasing this under a more standard open license (MIT, BSD, GPL)?

**Comment by dylanz** [comment]
Scott!  Weird, it was a very old BSD license for some reason.  I just updated it to MIT.  Thanks for the catch :)
