### ISSUE TITLE
use text instead of strings for raw_key, value

### ISSUE THREAD

**Issue by davidw** [dylanz/i18n_backend_database#2]
'string' ends up being 255 chars, which is not enough for longer bits of text.

```
 create_table :translations do |t|
   t.string   :key
-      t.string   :raw_key
-      t.string   :value
+      t.text     :raw_key
+      t.text     :value
   t.integer  :pluralization_index, :default => 1
   t.integer  :locale_id
 end
```

There should also be a little bit more room in the translation workspace:

```
--- a/lib/views/translations/translations.html.erb
+++ b/lib/views/translations/translations.html.erb
@@ -19,7 +19,7 @@
   <% remote_form_for([@locale, translation]) do |f| %>
 <p><%=h translation.default_locale_value || translation.raw_key %></p>
 <p>
-      <%= f.text_field :value %>
+      <%= f.text_field :value, :size => 128 %>
   <%= f.submit "Update" %>
 </p>
   <% end %>
```

That could also be made to be a bit 'clever', and use a text area for larger bits of text...

**Comment by davidw** [comment]
Oops, the key should be a text too.

**Comment by dylanz** [comment]
Ah, thanks for pointing those out David!  I did indeed change those fields to text in the application I integrated this into, but must have forgotten to update the repository.  I believe the "key" can be kept a varchar, as it's simply a digest.  Thank you!
