### ISSUE TITLE
Provide an easy way to restrict access to provided controllers

### ISSUE THREAD

**Issue by davidw** [dylanz/i18n_backend_database#3]
Currently, the two provided controllers let anyone and everyone access them, and require some fiddling to secure.  It would be better to make them secure by default.

**Comment by dylanz** [comment]
Indeed.  This is an exercise for the reader, as the authentication schemes on the controllers will vary per project.  It's usually something a simple before_filter can handle.  That said, the admin section could use a little love, as I think it's married to prototype at the moment, which should probably be extracted out to make it a bit more JS agnostic.  Thanks!

**Comment by davidw** [comment]
Maybe they should be 'off by default' as a security measure.  And/or mentioned in the install procedure.

**Comment by dylanz** [comment]
I added a bullet to the disclaimer section in the README, and also a FIXME comment in the controller itself.  Hopefully this will be clear enough.  Thanks David!
